-- =============================================
-- SQL para insertar los datos del patchbay
-- Ejecuta esto en el SQL Editor de Supabase
-- DESPUÉS de haber creado las tablas con schema.sql
-- =============================================

INSERT INTO patchbay_points (id, name, description, type) VALUES
(1, 'MIC LINE 01 PANEL 1', 'Description for MIC LINE 01 PANEL 1', 'standard'),
(2, 'MIC LINE 02 PANEL 1', 'Description for MIC LINE 02 PANEL 1', 'standard'),
(3, 'MIC LINE 03 PANEL 1', 'Description for MIC LINE 03 PANEL 1', 'standard'),
(4, 'MIC LINE 04 PANEL 1', 'Description for MIC LINE 04 PANEL 1', 'standard'),
(5, 'MIC LINE 05 PANEL 2', 'Description for MIC LINE 05 PANEL 2', 'standard'),
(6, 'MIC LINE 06 PANEL 2', 'Description for MIC LINE 06 PANEL 2', 'standard'),
(7, 'MIC LINE 07 PANEL 2', 'Description for MIC LINE 07 PANEL 2', 'standard'),
(8, 'MIC LINE 08 PANEL 2', 'Description for MIC LINE 08 PANEL 2', 'standard'),
(9, 'MIC LINE 09 PANEL 2', 'Description for MIC LINE 09 PANEL 2', 'standard'),
(10, 'MIC LINE 10 PANEL 2', 'Description for MIC LINE 10 PANEL 2', 'standard'),
(11, 'MIC LINE 11 PANEL 2', 'Description for MIC LINE 11 PANEL 2', 'standard'),
(12, 'MIC LINE 12 PANEL 2', 'Description for MIC LINE 12 PANEL 2', 'standard'),
(13, 'MIC LINE 13 PANEL 2', 'Description for MIC LINE 13 PANEL 2', 'standard'),
(14, 'MIC LINE 14 PANEL 2', 'Description for MIC LINE 14 PANEL 2', 'standard'),
(15, 'MIC LINE 15 PANEL 3', 'Description for MIC LINE 15 PANEL 3', 'standard'),
(16, 'MIC LINE 16 PANEL 3', 'Description for MIC LINE 16 PANEL 3', 'standard'),
(17, 'MIC LINE 17 PANEL 3', 'Description for MIC LINE 17 PANEL 3', 'standard'),
(18, 'MIC LINE 18 PANEL 3', 'Description for MIC LINE 18 PANEL 3', 'standard'),
(19, 'MIC LINE 19 PANEL 3', 'Description for MIC LINE 19 PANEL 3', 'standard'),
(20, 'MIC LINE 20 PANEL 3', 'Description for MIC LINE 20 PANEL 3', 'standard'),
(21, 'MIC LINE 21 PANEL 3', 'Description for MIC LINE 21 PANEL 3', 'standard'),
(22, 'MIC LINE 22 PANEL 3', 'Description for MIC LINE 22 PANEL 3', 'standard'),
(23, 'MIC LINE 23 PANEL 3', 'Description for MIC LINE 23 PANEL 3', 'standard'),
(24, 'MIC LINE 24 PANEL 3', 'Description for MIC LINE 24 PANEL 3', 'standard'),
(25, 'MIC LINE 25 ISO PANEL', 'Description for MIC LINE 25 ISO PANEL', 'standard'),
(26, 'MIC LINE 26 ISO PANEL', 'Description for MIC LINE 26 ISO PANEL', 'standard'),
(27, 'MIC LINE 27 ISO PANEL', 'Description for MIC LINE 27 ISO PANEL', 'standard'),
(28, 'MIC LINE 28 ISO PANEL', 'Description for MIC LINE 28 ISO PANEL', 'standard'),
(29, 'MIC LINE 29 ISO PANEL', 'Description for MIC LINE 29 ISO PANEL', 'standard'),
(30, 'MIC LINE 30 ISO PANEL', 'Description for MIC LINE 30 ISO PANEL', 'standard'),
(31, 'MIC LINE 31 ISO PANEL', 'Description for MIC LINE 31 ISO PANEL', 'standard'),
(32, 'MIC LINE 32 ISO PANEL', 'Description for MIC LINE 32 ISO PANEL', 'standard'),
(33, 'TIELINE 1 PANEL 1', 'Description for TIELINE 1 PANEL 1', 'standard'),
(34, 'TIELINE 2 PANEL 1', 'Description for TIELINE 2 PANEL 1', 'standard'),
(35, 'TIELINE 3 PANEL 2', 'Description for TIELINE 3 PANEL 2', 'standard'),
(36, 'TIELINE 4 PANEL 3', 'Description for TIELINE 4 PANEL 3', 'standard'),
(37, 'TIELINE 5 PANEL 3', 'Description for TIELINE 5 PANEL 3', 'standard'),
(38, 'TIELINE 6 PANEL 3', 'Description for TIELINE 6 PANEL 3', 'standard'),
(39, 'TIELINE 7 ISO PANEL', 'Description for TIELINE 7 ISO PANEL', 'standard'),
(40, 'TIELINE 8 ISO PANEL', 'Description for TIELINE 8 ISO PANEL', 'standard'),
(41, 'TIELINE 9 ISO PANEL', 'Description for TIELINE 9 ISO PANEL', 'standard'),
(42, 'TIELINE 10 ISO PANEL', 'Description for TIELINE 10 ISO PANEL', 'standard'),
(43, 'TIELINE 11 AMP PANEL', 'Description for TIELINE 11 AMP PANEL', 'standard'),
(44, 'TIELINE 12 AMP PANEL', 'Description for TIELINE 12 AMP PANEL', 'standard'),
(45, 'TIELINE 13 AMP PANEL', 'Description for TIELINE 13 AMP PANEL', 'standard'),
(46, 'TIELINE 14 AMP PANEL', 'Description for TIELINE 14 AMP PANEL', 'standard'),
(47, 'TIELINE 15 AMP PANEL', 'Description for TIELINE 15 AMP PANEL', 'standard'),
(48, 'TIELINE 16 AMP PANEL', 'Description for TIELINE 16 AMP PANEL', 'standard'),
(49, 'AVALON', 'Description for AVALON', 'standard'),
(50, 'UA-6176', 'Description for UA-6176', 'standard'),
(51, 'MANLEY A', 'Description for MANLEY A', 'standard'),
(52, 'MANLEY B', 'Description for MANLEY B', 'standard'),
(53, 'API 1', 'Description for API 1', 'standard'),
(54, 'API 2', 'Description for API 2', 'standard'),
(55, 'API 3', 'Description for API 3', 'standard'),
(56, 'API 4', 'Description for API 4', 'standard'),
(57, 'UA-4710 1', 'Description for UA-4710 1', 'standard'),
(58, 'UA-4710 2', 'Description for UA-4710 2', 'standard'),
(59, 'UA-4710 3', 'Description for UA-4710 3', 'standard'),
(60, 'UA-4710 4', 'Description for UA-4710 4', 'standard'),
(61, 'LANGEVIN 1', 'Description for LANGEVIN 1', 'standard'),
(62, 'LANGEVIN 2', 'Description for LANGEVIN 2', 'standard'),
(63, 'OCTO 1', 'Description for OCTO 1', 'standard'),
(64, 'OCTO 2', 'Description for OCTO 2', 'standard'),
(65, 'OCTO 3', 'Description for OCTO 3', 'standard'),
(66, 'OCTO 4', 'Description for OCTO 4', 'standard'),
(67, 'OCTO 5', 'Description for OCTO 5', 'standard'),
(68, 'OCTO 6', 'Description for OCTO 6', 'standard'),
(69, 'OCTO 7', 'Description for OCTO 7', 'standard'),
(70, 'OCTO 8', 'Description for OCTO 8', 'standard'),
(71, 'ISATWO 1', 'Description for ISATWO 1', 'standard'),
(72, 'ISATWO 2', 'Description for ISATWO 2', 'standard'),
(73, 'PRE 25 – MI', 'Description for PRE 25 – MI', 'standard'),
(74, 'PRE 26 – MI', 'Description for PRE 26 – MI', 'standard'),
(75, 'PRE 27 – MI', 'Description for PRE 27 – MI', 'standard'),
(76, 'PRE 28 – MI', 'Description for PRE 28 – MI', 'standard'),
(77, 'PRE 29 – MI', 'Description for PRE 29 – MI', 'standard'),
(78, 'PRE 30 – MI', 'Description for PRE 30 – MI', 'standard'),
(79, 'PRE 31 – MI', 'Description for PRE 31 – MI', 'standard'),
(80, 'PRE 32 – MI', 'Description for PRE 32 – MI', 'standard'),
(81, 'RND MBP SC SEND L', 'Description for RND MBP SC SEND L', 'standard'),
(82, 'RND MBP SC SEND R', 'Description for RND MBP SC SEND R', 'standard'),
(83, 'RND MBP SC RTN L', 'Description for RND MBP SC RTN L', 'standard'),
(84, 'RND MBP SC RTN R', 'Description for RND MBP SC RTN R', 'standard'),
(85, 'TIELINE 17 SLK PANEL', 'Description for TIELINE 17 SLK PANEL', 'standard'),
(86, 'TIELINE 18 SLK PANEL', 'Description for TIELINE 18 SLK PANEL', 'standard'),
(87, 'TIELINE 19 SLK PANEL', 'Description for TIELINE 19 SLK PANEL', 'standard'),
(88, 'TIELINE 20 SLK PANEL', 'Description for TIELINE 20 SLK PANEL', 'standard'),
(89, 'TIELINE 21 GUEST PANEL', 'Description for TIELINE 21 GUEST PANEL', 'standard'),
(90, 'TIELINE 22 GUEST PANEL', 'Description for TIELINE 22 GUEST PANEL', 'standard'),
(91, 'TIELINE 23 GUEST PANEL', 'Description for TIELINE 23 GUEST PANEL', 'standard'),
(92, 'TIELINE 24 GUEST PANEL', 'Description for TIELINE 24 GUEST PANEL', 'standard'),
(93, 'TIELINE 25 GUEST PANEL', 'Description for TIELINE 25 GUEST PANEL', 'standard'),
(94, 'TIELINE 26 GUEST PANEL', 'Description for TIELINE 26 GUEST PANEL', 'standard'),
(95, 'JBL 1', 'Description for JBL 1', 'standard'),
(96, 'JBL 2', 'Description for JBL 2', 'standard'),
(97, 'PRE 1 – LO AVALON', 'Description for PRE 1 – LO AVALON', 'standard'),
(98, 'PRE 2 – LO UA-6176', 'Description for PRE 2 – LO UA-6176', 'standard'),
(99, 'PRE 3 – LO MANLEY A', 'Description for PRE 3 – LO MANLEY A', 'standard'),
(100, 'PRE 4 – LO MANLEY B', 'Description for PRE 4 – LO MANLEY B', 'standard'),
(101, 'PRE 5 – LO API 1', 'Description for PRE 5 – LO API 1', 'standard'),
(102, 'PRE 6 – LO API 2', 'Description for PRE 6 – LO API 2', 'standard'),
(103, 'PRE 7 – LO API 3', 'Description for PRE 7 – LO API 3', 'standard'),
(104, 'PRE 8 – LO API 4', 'Description for PRE 8 – LO API 4', 'standard'),
(105, 'PRE 9 – LO UA-4710 1', 'Description for PRE 9 – LO UA-4710 1', 'standard'),
(106, 'PRE 10 – LO UA-4710 2', 'Description for PRE 10 – LO UA-4710 2', 'standard'),
(107, 'PRE 11 – LO UA-4710 3', 'Description for PRE 11 – LO UA-4710 3', 'standard'),
(108, 'PRE 12 – LO UA-4710 4', 'Description for PRE 12 – LO UA-4710 4', 'standard'),
(109, 'PRE 13 – LO LANGEVIN 1', 'Description for PRE 13 – LO LANGEVIN 1', 'standard'),
(110, 'PRE 14 – LO LANGEVIN 2', 'Description for PRE 14 – LO LANGEVIN 2', 'standard'),
(111, 'PRE 15 – LO OCTO 1', 'Description for PRE 15 – LO OCTO 1', 'standard'),
(112, 'PRE 16 – LO OCTO 2', 'Description for PRE 16 – LO OCTO 2', 'standard'),
(113, 'PRE 17 – LO OCTO 3', 'Description for PRE 17 – LO OCTO 3', 'standard'),
(114, 'PRE 18 – LO OCTO 4', 'Description for PRE 18 – LO OCTO 4', 'standard'),
(115, 'PRE 19 – LO OCTO 5', 'Description for PRE 19 – LO OCTO 5', 'standard'),
(116, 'PRE 20 – LO OCTO 6', 'Description for PRE 20 – LO OCTO 6', 'standard'),
(117, 'PRE 21 – LO OCTO 7', 'Description for PRE 21 – LO OCTO 7', 'standard'),
(118, 'PRE 22 – LO OCTO 8', 'Description for PRE 22 – LO OCTO 8', 'standard'),
(119, 'PRE 23 – LO ISATWO 1', 'Description for PRE 23 – LO ISATWO 1', 'standard'),
(120, 'PRE 24 – LO ISATWO 2', 'Description for PRE 24 – LO ISATWO 2', 'standard'),
(121, 'PRE 25 – LO', 'Description for PRE 25 – LO', 'standard'),
(122, 'PRE 26 – LO', 'Description for PRE 26 – LO', 'standard'),
(123, 'PRE 27 – LO', 'Description for PRE 27 – LO', 'standard'),
(124, 'PRE 28 – LO', 'Description for PRE 28 – LO', 'standard'),
(125, 'PRE 29 – LO', 'Description for PRE 29 – LO', 'standard'),
(126, 'PRE 30 – LO', 'Description for PRE 30 – LO', 'standard'),
(127, 'PRE 31 – LO', 'Description for PRE 31 – LO', 'standard'),
(128, 'PRE 32 – LO', 'Description for PRE 32 – LO', 'standard'),
(129, 'FO 1 UA 6176 LO COMP', 'Description for FO 1 UA 6176 LO COMP', 'standard'),
(130, 'FO 2 UA 4710 SEND 1', 'Description for FO 2 UA 4710 SEND 1', 'standard'),
(131, 'FO 3 UA 4710 SEND 2', 'Description for FO 3 UA 4710 SEND 2', 'standard'),
(132, 'FO 4 UA 4710 SEND 3', 'Description for FO 4 UA 4710 SEND 3', 'standard'),
(133, 'FO 5 UA 4710 SEND 4', 'Description for FO 5 UA 4710 SEND 4', 'standard'),
(134, 'FO 6', 'Description for FO 6', 'standard'),
(135, 'FO 7', 'Description for FO 7', 'standard'),
(136, 'FO 8', 'Description for FO 8', 'standard'),
(137, 'FO 9', 'Description for FO 9', 'standard'),
(138, 'FO 10', 'Description for FO 10', 'standard'),
(139, 'FO 11', 'Description for FO 11', 'standard'),
(140, 'FO 12', 'Description for FO 12', 'standard'),
(141, 'FO 13', 'Description for FO 13', 'standard'),
(142, 'FO 14', 'Description for FO 14', 'standard'),
(143, 'FO 15 0', 'Description for FO 15 0', 'standard'),
(144, 'FO 16 0', 'Description for FO 16 0', 'standard'),
(145, 'PROTOOLS LI 1', 'Description for PROTOOLS LI 1', 'standard'),
(146, 'PROTOOLS LI 2', 'Description for PROTOOLS LI 2', 'standard'),
(147, 'PROTOOLS LI 3', 'Description for PROTOOLS LI 3', 'standard'),
(148, 'PROTOOLS LI 4', 'Description for PROTOOLS LI 4', 'standard'),
(149, 'PROTOOLS LI 5', 'Description for PROTOOLS LI 5', 'standard'),
(150, 'PROTOOLS LI 6', 'Description for PROTOOLS LI 6', 'standard'),
(151, 'PROTOOLS LI 7', 'Description for PROTOOLS LI 7', 'standard'),
(152, 'PROTOOLS LI 8', 'Description for PROTOOLS LI 8', 'standard'),
(153, 'PROTOOLS LI 9', 'Description for PROTOOLS LI 9', 'standard'),
(154, 'PROTOOLS LI 10', 'Description for PROTOOLS LI 10', 'standard'),
(155, 'PROTOOLS LI 11', 'Description for PROTOOLS LI 11', 'standard'),
(156, 'PROTOOLS LI 12', 'Description for PROTOOLS LI 12', 'standard'),
(157, 'PROTOOLS LI 13', 'Description for PROTOOLS LI 13', 'standard'),
(158, 'PROTOOLS LI 14', 'Description for PROTOOLS LI 14', 'standard'),
(159, 'PROTOOLS LI 15', 'Description for PROTOOLS LI 15', 'standard'),
(160, 'PROTOOLS LI 16', 'Description for PROTOOLS LI 16', 'standard'),
(161, 'PROTOOLS LI 17', 'Description for PROTOOLS LI 17', 'standard'),
(162, 'PROTOOLS LI 18', 'Description for PROTOOLS LI 18', 'standard'),
(163, 'PROTOOLS LI 19', 'Description for PROTOOLS LI 19', 'standard'),
(164, 'PROTOOLS LI 20', 'Description for PROTOOLS LI 20', 'standard'),
(165, 'PROTOOLS LI 21', 'Description for PROTOOLS LI 21', 'standard'),
(166, 'PROTOOLS LI 22', 'Description for PROTOOLS LI 22', 'standard'),
(167, 'PROTOOLS LI 23', 'Description for PROTOOLS LI 23', 'standard'),
(168, 'PROTOOLS LI 24', 'Description for PROTOOLS LI 24', 'standard'),
(169, 'PROTOOLS LI 25', 'Description for PROTOOLS LI 25', 'standard'),
(170, 'PROTOOLS LI 26', 'Description for PROTOOLS LI 26', 'standard'),
(171, 'PROTOOLS LI 27', 'Description for PROTOOLS LI 27', 'standard'),
(172, 'PROTOOLS LI 28', 'Description for PROTOOLS LI 28', 'standard'),
(173, 'PROTOOLS LI 29', 'Description for PROTOOLS LI 29', 'standard'),
(174, 'PROTOOLS LI 30', 'Description for PROTOOLS LI 30', 'standard'),
(175, 'PROTOOLS LI 31', 'Description for PROTOOLS LI 31', 'standard'),
(176, 'PROTOOLS LI 32', 'Description for PROTOOLS LI 32', 'standard'),
(177, 'AVALON LI PRE', 'Description for AVALON LI PRE', 'standard'),
(178, 'UA 6176 LI PRE', 'Description for UA 6176 LI PRE', 'standard'),
(179, 'UA 6176 LI COMP', 'Description for UA 6176 LI COMP', 'standard'),
(180, 'UA 4710 LI 1', 'Description for UA 4710 LI 1', 'standard'),
(181, 'UA 4710 LI 2', 'Description for UA 4710 LI 2', 'standard'),
(182, 'UA 4710 LI 3', 'Description for UA 4710 LI 3', 'standard'),
(183, 'UA 4710 LI 4', 'Description for UA 4710 LI 4', 'standard'),
(184, 'UA 4710 RTN 1', 'Description for UA 4710 RTN 1', 'standard'),
(185, 'UA 4710 RTN 2', 'Description for UA 4710 RTN 2', 'standard'),
(186, 'UA 4710 RTN 3', 'Description for UA 4710 RTN 3', 'standard'),
(187, 'UA 4710 RTN 4', 'Description for UA 4710 RTN 4', 'standard'),
(188, 'LANGEVIN LI 1', 'Description for LANGEVIN LI 1', 'standard'),
(189, 'LANGEVIN LI 2', 'Description for LANGEVIN LI 2', 'standard'),
(190, 'FI 14', 'Description for FI 14', 'standard'),
(191, '0 FI 15', 'Description for 0 FI 15', 'standard'),
(192, '0 FI 16', 'Description for 0 FI 16', 'standard'),
(193, 'PROTOOLS LO 1 MAIN MON LO L', 'Description for PROTOOLS LO 1 MAIN MON LO L', 'standard'),
(194, 'PROTOOLS LO 2 MAIN MON LO R', 'Description for PROTOOLS LO 2 MAIN MON LO R', 'standard'),
(195, 'PROTOOLS LO 3 MAIN MON LO SL', 'Description for PROTOOLS LO 3 MAIN MON LO SL', 'standard'),
(196, 'PROTOOLS LO 4 MAIN MON LO SR', 'Description for PROTOOLS LO 4 MAIN MON LO SR', 'standard'),
(197, 'PROTOOLS LO 5 MAIN MON LO C', 'Description for PROTOOLS LO 5 MAIN MON LO C', 'standard'),
(198, 'PROTOOLS LO 6 MAIN MON LO LFE', 'Description for PROTOOLS LO 6 MAIN MON LO LFE', 'standard'),
(199, 'PROTOOLS LO 7 REAMP 1 – NF MON LO L', 'Description for PROTOOLS LO 7 REAMP 1 – NF MON LO L', 'standard'),
(200, 'PROTOOLS LO 8 REAMP 2 – NF MON LO R', 'Description for PROTOOLS LO 8 REAMP 2 – NF MON LO R', 'standard'),
(201, 'PROTOOLS LO 9 HEARBACK LO 01', 'Description for PROTOOLS LO 9 HEARBACK LO 01', 'standard'),
(202, 'PROTOOLS LO 10 HEARBACK LO 02', 'Description for PROTOOLS LO 10 HEARBACK LO 02', 'standard'),
(203, 'PROTOOLS LO 11 HEARBACK LO 03', 'Description for PROTOOLS LO 11 HEARBACK LO 03', 'standard'),
(204, 'PROTOOLS LO 12 HEARBACK LO 04', 'Description for PROTOOLS LO 12 HEARBACK LO 04', 'standard'),
(205, 'PROTOOLS LO 13 HEARBACK LO 05', 'Description for PROTOOLS LO 13 HEARBACK LO 05', 'standard'),
(206, 'PROTOOLS LO 14 HEARBACK LO 06', 'Description for PROTOOLS LO 14 HEARBACK LO 06', 'standard'),
(207, 'PROTOOLS LO 15 HEARBACK LO 07', 'Description for PROTOOLS LO 15 HEARBACK LO 07', 'standard'),
(208, 'PROTOOLS LO 16 HEARBACK LO 08', 'Description for PROTOOLS LO 16 HEARBACK LO 08', 'standard'),
(209, 'PROTOOLS LO 17', 'Description for PROTOOLS LO 17', 'standard'),
(210, 'PROTOOLS LO 18', 'Description for PROTOOLS LO 18', 'standard'),
(211, 'PROTOOLS LO 19', 'Description for PROTOOLS LO 19', 'standard'),
(212, 'PROTOOLS LO 20', 'Description for PROTOOLS LO 20', 'standard'),
(213, 'PROTOOLS LO 21', 'Description for PROTOOLS LO 21', 'standard'),
(214, 'PROTOOLS LO 22', 'Description for PROTOOLS LO 22', 'standard'),
(215, 'PROTOOLS LO 23', 'Description for PROTOOLS LO 23', 'standard'),
(216, 'PROTOOLS LO 24', 'Description for PROTOOLS LO 24', 'standard'),
(217, 'PROTOOLS LO 25', 'Description for PROTOOLS LO 25', 'standard'),
(218, 'PROTOOLS LO 26', 'Description for PROTOOLS LO 26', 'standard'),
(219, 'PROTOOLS LO 27', 'Description for PROTOOLS LO 27', 'standard'),
(220, 'PROTOOLS LO 28', 'Description for PROTOOLS LO 28', 'standard'),
(221, 'PROTOOLS LO 29', 'Description for PROTOOLS LO 29', 'standard'),
(222, 'PROTOOLS LO 30', 'Description for PROTOOLS LO 30', 'standard'),
(223, 'PROTOOLS LO 31 JBL 1', 'Description for PROTOOLS LO 31 JBL 1', 'standard'),
(224, 'PROTOOLS LO 32 JBL 2', 'Description for PROTOOLS LO 32 JBL 2', 'standard'),
(225, 'FO 1 – S17 RND MBP LO L', 'Description for FO 1 – S17 RND MBP LO L', 'standard'),
(226, 'FO 2 – S18 RND MBP LO R', 'Description for FO 2 – S18 RND MBP LO R', 'standard'),
(227, 'FO 3 – S19 SSL FUSION LO L', 'Description for FO 3 – S19 SSL FUSION LO L', 'standard'),
(228, 'FO 4 – S20 SSL FUSION LO R', 'Description for FO 4 – S20 SSL FUSION LO R', 'standard'),
(229, 'FO 5 – S21 SSL FUSION SEND L', 'Description for FO 5 – S21 SSL FUSION SEND L', 'standard'),
(230, 'FO 6 – S22 SSL FUSION SEND R', 'Description for FO 6 – S22 SSL FUSION SEND R', 'standard'),
(231, 'FO 7 – S23 LB1 LO – RND 511 1', 'Description for FO 7 – S23 LB1 LO – RND 511 1', 'standard'),
(232, 'FO 8 – S24 LB2 LO – RND 511 2', 'Description for FO 8 – S24 LB2 LO – RND 511 2', 'standard'),
(233, 'FO 9 – S25 LB3 LO', 'Description for FO 9 – S25 LB3 LO', 'standard'),
(234, 'FO 10 – S26 LB4 LO', 'Description for FO 10 – S26 LB4 LO', 'standard'),
(235, 'FO 11 – S27 LB5 LO', 'Description for FO 11 – S27 LB5 LO', 'standard'),
(236, 'FO 12 – S28 LB6 LO', 'Description for FO 12 – S28 LB6 LO', 'standard'),
(237, 'FO 13 – S29 LB7 LO', 'Description for FO 13 – S29 LB7 LO', 'standard'),
(238, 'FO 14 – S30 LB8 LO', 'Description for FO 14 – S30 LB8 LO', 'standard'),
(239, 'FO 15 – S31 LB9 LO', 'Description for FO 15 – S31 LB9 LO', 'standard'),
(240, 'FO 16 – S32 LB10 LO', 'Description for FO 16 – S32 LB10 LO', 'standard'),
(241, 'MAIN MON LI L', 'Description for MAIN MON LI L', 'standard'),
(242, 'MAIN MON LI R', 'Description for MAIN MON LI R', 'standard'),
(243, 'MAIN MON LI SL', 'Description for MAIN MON LI SL', 'standard'),
(244, 'MAIN MON LI SR', 'Description for MAIN MON LI SR', 'standard'),
(245, 'MAIN MON LI C', 'Description for MAIN MON LI C', 'standard'),
(246, 'MAIN MON LI LFE', 'Description for MAIN MON LI LFE', 'standard'),
(247, 'NF MON LI L', 'Description for NF MON LI L', 'standard'),
(248, 'NF MON LI R', 'Description for NF MON LI R', 'standard'),
(249, 'HEARBACK LI 01', 'Description for HEARBACK LI 01', 'standard'),
(250, 'HEARBACK LI 02', 'Description for HEARBACK LI 02', 'standard'),
(251, 'HEARBACK LI 03', 'Description for HEARBACK LI 03', 'standard'),
(252, 'HEARBACK LI 04', 'Description for HEARBACK LI 04', 'standard'),
(253, 'HEARBACK LI 05', 'Description for HEARBACK LI 05', 'standard'),
(254, 'HEARBACK LI 06', 'Description for HEARBACK LI 06', 'standard'),
(255, 'HEARBACK LI 07', 'Description for HEARBACK LI 07', 'standard'),
(256, 'HEARBACK LI 08', 'Description for HEARBACK LI 08', 'standard'),
(257, '-', 'Description for -', 'standard'),
(258, '-', 'Description for -', 'standard'),
(259, '-', 'Description for -', 'standard'),
(260, '-', 'Description for -', 'standard'),
(261, '-', 'Description for -', 'standard'),
(262, '-', 'Description for -', 'standard'),
(263, '-', 'Description for -', 'standard'),
(264, '-', 'Description for -', 'standard'),
(265, '-', 'Description for -', 'standard'),
(266, '-', 'Description for -', 'standard'),
(267, '-', 'Description for -', 'standard'),
(268, '-', 'Description for -', 'standard'),
(269, '-', 'Description for -', 'standard'),
(270, '-', 'Description for -', 'standard'),
(271, '-', 'Description for -', 'standard'),
(272, '-', 'Description for -', 'standard'),
(273, 'RND MBP LI L', 'Description for RND MBP LI L', 'standard'),
(274, 'RND MBP LI R', 'Description for RND MBP LI R', 'standard'),
(275, 'SSL FUSION LI L', 'Description for SSL FUSION LI L', 'standard'),
(276, 'SSL FUSION LI R', 'Description for SSL FUSION LI R', 'standard'),
(277, 'SSL FUSION RTN L', 'Description for SSL FUSION RTN L', 'standard'),
(278, 'SSL FUSION RTN R', 'Description for SSL FUSION RTN R', 'standard'),
(279, 'LB1 LI – RND 511 1', 'Description for LB1 LI – RND 511 1', 'standard'),
(280, 'LB2 LI – RND 511 2', 'Description for LB2 LI – RND 511 2', 'standard'),
(281, 'LB3 LI', 'Description for LB3 LI', 'standard'),
(282, 'LB4 LI', 'Description for LB4 LI', 'standard'),
(283, 'LB5 LI', 'Description for LB5 LI', 'standard'),
(284, 'LB6 LI', 'Description for LB6 LI', 'standard'),
(285, 'LB7 LI', 'Description for LB7 LI', 'standard'),
(286, 'LB8 LI', 'Description for LB8 LI', 'standard'),
(287, 'LB9 LI', 'Description for LB9 LI', 'standard'),
(288, 'LB10 LI', 'Description for LB10 LI', 'standard');

-- Actualizar la secuencia para que el próximo ID sea mayor al último insertado
SELECT setval('patchbay_points_id_seq', (SELECT MAX(id) FROM patchbay_points));
